package com.school.entity.query;

import lombok.Data;

/**
 * 分页查询基础类
 */
@Data
public class PageDomain {

    /**
     * 当前记录起始索引 (计算公式: (pageNum - 1) * pageSize)
     * 这个字段通常不在 Controller 接收，而是在 Service 或 Mapper 层根据 pageNum 和 pageSize 计算得出。
     * MybatisPlus 分页插件会自动处理分页逻辑，通常不需要手动传递 limit 参数。
     * 因此，这个字段可以省略，或者仅作为内部计算使用。
     */
    // private Integer offset;

    /**
     * 每页显示记录数
     */
    private Integer pageSize = 10; // 默认每页10条

    /**
     * 当前页码
     */
    private Integer pageNum = 1; // 默认第一页

    /**
     * 排序列
     * 例如: "create_time" 或 "id"
     */
    private String orderByColumn;

    /**
     * 排序的方向 "desc" 或者 "asc"
     */
    private String isAsc = "asc"; // 默认升序

    // Getters and setters are generated by Lombok
} 